# Generated by Django 5.2.3 on 2025-06-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnderConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_under_construction', models.BooleanField(default=False)),
                ('uc_note', models.TextField(blank=True, help_text='NOTE FOR UNDER CONSTRUCTION MODE.', null=True)),
                ('uc_duration', models.DateTimeField(blank=True, help_text='End date and time for under construction mode.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
