# Generated by Django 5.2.1 on 2025-05-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
