# Generated by Django 5.2.1 on 2025-05-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_test_age_alter_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='number',
            field=models.IntegerField(),
        ),
    ]
