# Generated by Django 5.2 on 2025-05-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_musician_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='address',
            field=models.CharField(default='non values', max_length=100),
        ),
    ]
