# Generated by Django 5.2.4 on 2025-07-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_profile_image_alter_student_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='profile_image/default.jpg', upload_to='profile_images/'),
            preserve_default=False,
        ),
    ]
