# Generated by Django 5.2 on 2025-06-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=290)),
                ('email', models.CharField(verbose_name=290)),
                ('password', models.CharField(verbose_name=290)),
            ],
        ),
    ]
