# Generated by Django 5.2.3 on 2025-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_city',
            field=models.CharField(choices=[('Indore', 'Indore'), ('Delhi', 'Delhi'), ('Pune', 'Pune'), ('Hydrabad', 'Hydrabad'), ('Bangalore', 'Bangalore')], max_length=50),
        ),
    ]
