# Generated by Django 5.2.3 on 2025-07-03 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(verbose_name=230)),
                ('center_city', models.CharField(verbose_name=230)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('examsenter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.examsenter')),
                ('name', models.CharField(verbose_name=230)),
                ('roll', models.IntegerField()),
            ],
            bases=('student.examsenter',),
        ),
    ]
